(()=>{
const F=(n,w=1200)=>`https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(n.replaceAll(' ','_'))}?width=${w}`,P=n=>`https://commons.wikimedia.org/wiki/File:${encodeURIComponent(n.replaceAll(' ','_'))}`,M=q=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`,E=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const D={
'Sevilla':{f:'Parque de María Luisa - Seville - Plaza de España - Puente de Castilla (14704804486).jpg',x:[['Plaza de España','"Plaza de España" Sevilla'],['Patio de las Doncellas · Real Alcázar','"Patio de las Doncellas" Sevilla'],['Catedral y Giralda','"Giralda" "Catedral de Sevilla"'],['Barrio de Santa Cruz','"Barrio de Santa Cruz" Sevilla'],['Torre del Oro','"Torre del Oro" Sevilla'],['Puente de Triana','"Puente de Triana" Sevilla'],['Metropol Parasol','"Metropol Parasol" Sevilla'],['Parque de María Luisa','"Parque de María Luisa" Sevilla'],['Casa de Pilatos','"Casa de Pilatos" Sevilla'],['Río Guadalquivir','Guadalquivir Sevilla panorama']]},
'Córdoba':{f:'Mezquita-catedral de Córdoba interior 4.jpg',x:[['Arcos de la Mezquita-Catedral','"Mezquita-Catedral de Córdoba" arches interior'],['Puente Romano','"Puente Romano de Córdoba"'],['Calleja de las Flores','"Calleja de las Flores" Córdoba'],['Jardines del Alcázar','"Alcázar de los Reyes Cristianos" gardens'],['Patio de los Naranjos','"Patio de los Naranjos" Córdoba'],['Judería','"Judería de Córdoba" streets'],['Plaza de la Corredera','"Plaza de la Corredera" Córdoba'],['Palacio de Viana · patios','"Palacio de Viana" Córdoba patios'],['Medina Azahara','"Medina Azahara" Córdoba'],['Torre de la Calahorra','"Torre de la Calahorra" Córdoba']]},
'Granada':{f:'Alhambra Granada Spain.jpg',x:[['Alhambra panorámica','Alhambra Granada panorama'],['Patio de los Leones','"Patio de los Leones" Alhambra'],['Jardines del Generalife','Generalife gardens Granada'],['Albaicín','Albaicín Granada panorama'],['Mirador de San Nicolás','"Mirador de San Nicolás" Granada'],['Carrera del Darro','"Carrera del Darro" Granada'],['Sacromonte','Sacromonte Granada cave houses'],['Catedral de Granada','"Catedral de Granada"'],['Paseo de los Tristes','"Paseo de los Tristes" Granada'],['Realejo','Realejo Granada streets']]},
'Ronda':{f:'Ronda Spain Puente-Nuevo-de-Ronda-01.jpg',x:[['Puente Nuevo','"Puente Nuevo" Ronda'],['Tajo de Ronda','"Tajo de Ronda" panorama'],['Mirador de Aldehuela','"Mirador de Aldehuela" Ronda'],['Casa del Rey Moro','"Casa del Rey Moro" Ronda'],['Baños Árabes','"Baños Árabes de Ronda"'],['Plaza Duquesa de Parcent','"Plaza Duquesa de Parcent" Ronda'],['Alameda del Tajo','"Alameda del Tajo" Ronda'],['Murallas','Ronda city walls'],['Puente Viejo','"Puente Viejo" Ronda'],['Ronda panorámica','Ronda Spain panorama']]},
'Setenil de las Bodegas':{f:'Setenil de las Bodegas - 006 (30708389305).jpg',x:[['Cuevas del Sol','"Cuevas del Sol" Setenil'],['Cuevas de la Sombra','"Cuevas de la Sombra" Setenil'],['Casas bajo la roca','Setenil de las Bodegas cave houses'],['Castillo','Setenil de las Bodegas castle'],['Torreón','Setenil de las Bodegas tower'],['Iglesia de la Encarnación','"Iglesia de la Encarnación" Setenil'],['Mirador del Carmen','"Mirador del Carmen" Setenil'],['Calle Herrería','"Calle Herrería" Setenil'],['Panorámica del pueblo','Setenil de las Bodegas panorama'],['Río Guadalporcún','Guadalporcun Setenil']]},
'Zahara de la Sierra':{f:'Panorama of Zahara de la Sierra, Cádiz.jpg',x:[['Panorámica de Zahara','Zahara de la Sierra panorama'],['Castillo','Zahara de la Sierra castle'],['Torre del Homenaje','"Torre del Homenaje" Zahara de la Sierra'],['Embalse Zahara-El Gastor','Zahara El Gastor reservoir'],['Callejuelas blancas','Zahara de la Sierra white streets'],['Plaza Lepanto','"Plaza Lepanto" Zahara de la Sierra'],['Santa María de la Mesa','"Santa María de la Mesa" Zahara'],['Miradores','Zahara de la Sierra viewpoint'],['Pueblo blanco','Zahara de la Sierra white village'],['Sierra de Grazalema','Zahara de la Sierra Grazalema landscape']]},
'Soportújar':{f:'Soportújar, en Granada (España).jpg',x:[['Panorámica','Soportújar Granada panorama'],['Ojo de la Bruja','"Ojo de la Bruja" Soportújar'],['Fuente de las Brujas','"Fuente de las Brujas" Soportújar'],['Era de los Aquelarres','"Era de los Aquelarres" Soportújar'],['Casa de Baba Yaga','"Baba Yaga" Soportújar'],['Dragón de Soportújar','dragon Soportújar Granada'],['Miradores','Soportújar viewpoint Alpujarra'],['Calles blancas','Soportújar white village streets'],['Rincones de brujería','Soportújar witches village'],['Sierra Nevada','Soportújar Sierra Nevada view']]},
'Pampaneira':{f:'Pampaneira-Alpujarra (3).jpg',x:[['Panorámica','Pampaneira panorama Alpujarra'],['Plaza de la Libertad','"Plaza de la Libertad" Pampaneira'],['Iglesia de la Santa Cruz','"Iglesia de la Santa Cruz" Pampaneira'],['Calle Verónica','"Calle Verónica" Pampaneira'],['Tinaos tradicionales','Pampaneira tinao'],['Acequias por las calles','Pampaneira street water channel'],['Fuente de San Antonio','"Fuente de San Antonio" Pampaneira'],['Artesanía y jarapas','Pampaneira crafts rugs'],['Barranco de Poqueira','Pampaneira Barranco de Poqueira'],['Casas blancas','Pampaneira white houses']]},
'Bubión':{f:'Bubión (5118904986).jpg',x:[['Panorámica','Bubión panorama Alpujarra'],['Bubión y Sierra Nevada','Bubión Sierra Nevada'],['Iglesia','Bubión church Granada'],['Casa Alpujarreña','"Casa Alpujarreña" Bubión'],['Tinaos','Bubión tinao'],['Calles blancas','Bubión white streets'],['Barranco de Poqueira','Bubión Barranco de Poqueira'],['Arquitectura alpujarreña','Bubión traditional houses'],['Vista del pueblo','Bubión village panorama'],['Miradores de montaña','Bubión viewpoint mountains']]},
'Capileira':{f:'Capileira - 2012-10-07 - Jorge Franganillo.jpg',x:[['Panorámica','Capileira panorama'],['Capileira y Sierra Nevada','Capileira Sierra Nevada'],['Iglesia','Capileira church'],['Calles blancas','Capileira white streets'],['Tinaos tradicionales','Capileira tinao'],['Fuentes del pueblo','Capileira fountain'],['Barranco de Poqueira','Capileira Barranco de Poqueira'],['Casa Museo Pedro Antonio de Alarcón','"Pedro Antonio de Alarcón" Capileira museum'],['Miradores','Capileira viewpoint'],['Arquitectura alpujarreña','Capileira traditional houses']]},
'Toledo':{f:'Panorama-view-Toledo-Spain.jpg',x:[['Mirador del Valle','"Mirador del Valle" Toledo'],['Catedral','"Catedral de Toledo"'],['Alcázar','"Alcázar de Toledo"'],['Puente de San Martín','"Puente de San Martín" Toledo'],['Puerta de Bisagra','"Puerta de Bisagra" Toledo'],['Santa María la Blanca','"Santa María la Blanca" Toledo'],['San Juan de los Reyes','"San Juan de los Reyes" Toledo'],['Plaza de Zocodover','"Plaza de Zocodover" Toledo'],['Cristo de la Luz','"Cristo de la Luz" Toledo'],['Panorámica de Toledo','Toledo Spain panorama']]},
'Consuegra':{f:'Windmills of Consuegra (6933229482).jpg',x:[['Molinos','Consuegra windmills'],['Castillo de la Muela','Consuegra castle La Muela'],['Cerro Calderico','"Cerro Calderico" Consuegra'],['Molino Bolero','"Molino Bolero" Consuegra'],['Molinos y paisaje','Consuegra windmills landscape'],['Plaza de España','"Plaza de España" Consuegra'],['Santa María la Mayor','"Santa María la Mayor" Consuegra'],['Paisaje manchego','Consuegra La Mancha landscape'],['Calle hacia los molinos','Consuegra street windmills'],['Vista del cerro','Consuegra hill windmills']]},
'Almagro':{f:'Almagro-Plaza-Mayor.jpg',x:[['Plaza Mayor','"Plaza Mayor de Almagro"'],['Corral de Comedias','"Corral de Comedias de Almagro"'],['Teatro Municipal','"Teatro Municipal de Almagro"'],['Convento de la Asunción','"Asunción de Calatrava" Almagro'],['Palacio de los Maestrales','"Palacio de los Maestrales" Almagro'],['Museo Nacional del Teatro','"Museo Nacional del Teatro" Almagro'],['Casas nobles','Almagro Spain historic houses'],['San Agustín','"San Agustín" Almagro church'],['Soportales verdes','Almagro green arcades'],['Centro histórico','Almagro Spain old town']]},
'Baeza':{f:'Baeza Plaza de Santa Maria.jpg',x:[['Plaza de Santa María','"Plaza de Santa María" Baeza'],['Catedral','"Catedral de Baeza"'],['Fuente de Santa María','"Fuente de Santa María" Baeza'],['Palacio de Jabalquinto','"Palacio de Jabalquinto"'],['Antigua Universidad','"Antigua Universidad de Baeza"'],['Plaza del Pópulo','"Plaza del Pópulo" Baeza'],['Fuente de los Leones','"Fuente de los Leones" Baeza'],['Paseo de las Murallas','"Paseo de las Murallas" Baeza'],['Olivares','Baeza olive groves'],['Centro histórico','Baeza Spain old town']]},
'Úbeda':{f:'Sacra Capilla del Salvador, en Úbeda (Jaén, España).jpg',x:[['Plaza Vázquez de Molina','"Plaza Vázquez de Molina" Úbeda'],['Sacra Capilla del Salvador','"Sacra Capilla del Salvador" Úbeda'],['Palacio Vázquez de Molina','"Palacio Vázquez de Molina"'],['Santa María de los Reales Alcázares','"Santa María de los Reales Alcázares"'],['Hospital de Santiago','"Hospital de Santiago" Úbeda'],['Sinagoga del Agua','"Sinagoga del Agua" Úbeda'],['Calle Real','"Calle Real" Úbeda'],['Miradores sobre olivares','Úbeda olive groves viewpoint'],['Casa Mudéjar','"Casa Mudéjar" Úbeda'],['Centro histórico','Úbeda Spain old town']]},
'Cazorla':{f:'Cazorla, Spain.jpg',x:[['Panorámica','Cazorla Spain panorama'],['Castillo de la Yedra','"Castillo de la Yedra" Cazorla'],['Ruinas de Santa María','"Ruinas de Santa María" Cazorla'],['Bóveda del río Cerezuelo','"Bóveda del río Cerezuelo" Cazorla'],['Plaza de Santa María','"Plaza de Santa María" Cazorla'],['Balcón de Zabaleta','"Balcón de Zabaleta" Cazorla'],['Castillo de las Cinco Esquinas','"Cinco Esquinas" Cazorla castle'],['Virgen de la Cabeza','"Virgen de la Cabeza" Cazorla ermita'],['Sierra de Cazorla','Sierra de Cazorla landscape'],['Pueblo y sierra','Cazorla village mountains']]}}
const ORDER=[['Sevilla','Córdoba','Granada'],['Ronda','Setenil de las Bodegas','Zahara de la Sierra','Granada'],['Soportújar','Pampaneira','Bubión','Capileira','Granada'],['Toledo','Consuegra','Almagro','Baeza','Granada'],['Úbeda','Baeza','Cazorla','Granada']];
const C='tour-v4:',gc=k=>{try{let v=JSON.parse(localStorage.getItem(C+k));return v&&Date.now()-v.t<6048e5?v.d:null}catch{return null}},sc=(k,d)=>{try{localStorage.setItem(C+k,JSON.stringify({t:Date.now(),d}))}catch{}};
async function img(q){let c=gc(q);if(c)return c;let u=new URL('https://commons.wikimedia.org/w/api.php'),z={action:'query',generator:'search',gsrsearch:`${q} filetype:bitmap`,gsrnamespace:6,gsrlimit:10,prop:'imageinfo',iiprop:'url|size',iiurlwidth:1200,format:'json',origin:'*'};Object.entries(z).forEach(([k,v])=>u.searchParams.set(k,v));let r=await fetch(u),j=await r.json(),bad=/\b(map|mapa|plan|plano|diagram|logo|escudo|flag|bandera|coat of arms|icon|poster|stamp|sello|locator)\b/i,a=Object.values(j.query?.pages||{}).map((p,i)=>{let x=p.imageinfo?.[0];return x?{src:x.thumburl||x.url,page:x.descriptionurl||`https://commons.wikimedia.org/wiki/${encodeURIComponent(p.title)}`,file:p.title.replace(/^File:/,''),w:x.width||0,h:x.height||0,i}:null}).filter(Boolean).filter(x=>!bad.test(x.file)&&x.w>=800&&x.h>=500&&x.w/x.h>.68&&x.w/x.h<2.7).sort((a,b)=>a.i-b.i);if(!a.length)throw 0;sc(q,a[0]);return a[0]}
async function pool(a,n,f){let i=0;await Promise.all(Array.from({length:Math.min(n,a.length)},async()=>{while(i<a.length){let k=i++;await f(a[k],k)}}))}
function patch(){ORDER.forEach((row,ri)=>row.forEach((name,pi)=>{let old=document.getElementById(`g-r${ri+1}-${pi}`);if(!old||old.dataset.curated)return;let d=D[name],g=document.createElement('div');g.className='gallery';g.id=`curated-r${ri+1}-${pi}`;g.dataset.curated='1';g.innerHTML=d.x.map(([t])=>`<figure class="photo curatedPhoto"><div class="tourismSkeleton">${E(t)}</div></figure>`).join('');old.replaceWith(g);let cards=[...g.children];pool(d.x,3,async([t,q],i)=>{let x,fb=false;try{x=await img(q)}catch{fb=true;x={src:F(d.f),page:P(d.f)}}cards[i].classList.toggle('fallbackPhoto',fb);cards[i].innerHTML=`<img loading="lazy" referrerpolicy="no-referrer" src="${x.src}" alt="${E(t)} en ${E(name)}" onerror="this.onerror=null;this.src='${F(d.f)}'"><div class="curatedLinks"><a href="${M(`${t}, ${name}, España`)}" target="_blank" rel="noopener" title="Abrir en Google Maps">⌖</a><a href="${x.page}" target="_blank" rel="noopener" title="Crédito y licencia">↗</a></div><figcaption><strong>${E(t)}</strong><span>${E(name)} · lugar turístico real</span></figcaption>`})}))}
let link=document.createElement('link');link.rel='stylesheet';link.href='photos-v2.css?v=4';document.head.appendChild(link);if(document.readyState==='loading')addEventListener('DOMContentLoaded',()=>setTimeout(patch,0));else setTimeout(patch,0);setTimeout(patch,1200);
})();
